name = "avalon-bot"
type = "webpack"

account_id = "xxxxxxxxxxxxx"
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2021-11-09"

[vars]
SLACK_TOKEN = "xoxb-xxxxx-xxxxxxx-xxxxxxx"
BROADCAST_SLACK_CHANNEL = "#avalon"
MIN_PLAYERS = "5"
MAX_PLAYERS = "10"
TEST_SLACK_USERNAME = "xxxxx"